# Change these first
owner: XLorPaste # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: XLorPaste
    url: https://xlorpaste.cn/
  - name: XLorPaste API
    url: https://api.xlorpaste.cn/
  - name: XLorPaste View Code API
    url: https://api.xlorpaste.cn/towqab
#   - name: Google
#     url: https://www.google.com
#   - name: Wikipedia
#     url: https://en.wikipedia.org
#   - name: Hacker News
#     url: https://news.ycombinator.com
#   - name: Broken Site
#     url: https://thissitedoesnotexist.com
#   - name: Secret Site
#     url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.xlorpaste.cn
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://xlorpaste.cn/favicon.ico
  name: XLorPaste Status
  introTitle: XLorPaste Status Monitor
  introMessage: Use **real-time** data from our [Github repository](https://github.com/koj-co/upptime) powered by open-source uptime monitor **Upptime** and **GitHub**.
  navbar:
    - title: Status
      href: /
    - title: XLorPaste
      href: https://xlorpaste.cn/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
